---
deployment:
  tasks:
    - export DEPLOYPATH=/home/shfcoid/webtest.shf.co.id
    - export NPMPATH=/home/shfcoid/.nvm/versions/node/v15.6.0/bin
    - /bin/cp -af . $DEPLOYPATH #copy all from root
    - /bin/chmod 757 $DEPLOYPATH/bash/deploy.sh
    - /bin/chmod 757 $DEPLOYPATH/bash/install.sh
    - /bin/chmod 757 $DEPLOYPATH/bash/update.sh
    - /bin/chmod 755 $DEPLOYPATH
    - cd $DEPLOYPATH
    - $DEPLOYPATH/deploy.sh 2>&1
