---
deployment:
  tasks:
    - export DEPLOYPATH=/home/shfcoid/webdev.shf.co.id/
    - /bin/cp -Rn /home/shfcoid/repositories/laravel-seb-shf/public/* $DEPLOYPATH/
    #    - /bin/cp -r ./public/* $DEPLOYPATH/
    #- /bin/cp ./public/js/*.js $DEPLOYPATH/js
    #- /bin/cp ./public/css/*.css $DEPLOYPATH/css
