---
deployment:
  tasks:
    - export DEPLOYPATH=/home/shfcoid/webtest.shf.co.id
    - /bin/cp -af . $DEPLOYPATH #copy all from root
    - /bin/chmod 757 $DEPLOYPATH/deploy.sh
    - /bin/chmod 757 $DEPLOYPATH/build.sh
    - npm install
    - npm run dev
    # - $DEPLOYPATH/deploy.sh 2>&1
